export const MY_SKILLS = {
  onAverage: [
    "JavaScript",
    "TypeScript",
    "React",
    "Redux",
    "Next Js",
    "Express",
    "POO",
    "Ajax",
    "API integration",
    "HTML",
    "CSS",
    "SASS",
    "BEM",
    "Response Design",
  ],
  improving: [
    "Jest",
    "NodeJs",
    "Gatsby",
    "MongoDB",
    "Graphql",
    "PostgreSql",
    "MySql",
    "Firebase",
    "Webpack",
    "Functional Programming",
    "Java",
    "CSS animations",
    "GIT",
  ],
  tools: ["Github", "Figma", "Visual Studio Code"],
  hobbies: ["Jiu Jitsu", "Make clay sculptures"],
};
